import React, { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { jsPDF } from "jspdf";
import DashboardLayout from "../../layouts/DashboardLayout";
import BrainHero from "../../assets/brainhome.png";
import { fetchPatientBrainScan } from "../../services/patientService";
import type { PatientBrainRecord } from "../../data/patientBrainData";
import { useAuth } from "../../context/AuthContext";
import { LoadingState } from "../../components/ui/LoadingState";
import { ErrorState } from "../../components/ui/ErrorState";
import { getLatestDoneSession, getSession } from "../../services/localScanStore";

const DEFAULT_PATIENT_ID = "P-0001";

const PatientBrainDashboard: React.FC = () => {
  const { user } = useAuth();
  const [searchParams] = useSearchParams();
  const [data, setData] = useState<PatientBrainRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const sessionId = searchParams.get("sessionId");
  const patientId = user?.patientId ?? DEFAULT_PATIENT_ID;

  const mapSession = () => {
    const session = sessionId
      ? getSession(sessionId)
      : getLatestDoneSession(patientId, "brain");
    if (
      !session ||
      session.status !== "done" ||
      session.type !== "brain" ||
      session.patientId !== patientId ||
      !session.data?.patient
    ) {
      return null;
    }
    return session.data.patient as PatientBrainRecord;
  };

  useEffect(() => {
    setLoading(true);
    setError(null);
    const load = async () => {
      try {
        const sessionData = mapSession();
        if (sessionData) {
          setData(sessionData);
          return;
        }
        const record = await fetchPatientBrainScan(patientId);
        if (!record) setError("No brain scan data found.");
        setData(record);
      } catch (err: any) {
        setError(err?.message ?? "Unable to load brain scan.");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [patientId, sessionId]);

  const exportPdf = () => {
    if (!data) return;
    const doc = new jsPDF();
    doc.text("InsightX Diagnostic Report", 10, 20);
    doc.text(`Patient: ${data.name} (${data.patientId})`, 10, 30);
    doc.text("Scan type: Brain", 10, 38);
    doc.text(`Date: ${new Date().toISOString()}`, 10, 46);
    doc.text("Key metrics:", 10, 58);
    doc.text(`- Oxygenation: ${data.oxygenation}%`, 14, 66);
    doc.text(`- Stress: ${data.stress}`, 14, 74);
    doc.text(`- Focus: ${data.focus}`, 14, 82);
    doc.text(`- Score: ${data.score}`, 14, 90);
    doc.text(`Summary: ${data.doctorSummary}`, 10, 104);
    doc.text("Generated by InsightX (mock)", 10, 130);
    doc.save(`InsightX_Patient_Brain_${data.patientId}.pdf`);
  };

  if (loading) {
    return (
      <DashboardLayout>
        <LoadingState message="Loading your brain scan..." />
      </DashboardLayout>
    );
  }

  if (error || !data) {
    return (
      <DashboardLayout>
        <ErrorState message={error ?? "No brain scan data found."} />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="space-y-4 min-w-0">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
          <div>
            <h1 className="text-lg font-semibold">Your Brain Scan Overview</h1>
            <p className="text-xs text-slate-500">Scan ID: {data.scanId}</p>
          </div>
          <div className="flex items-center gap-2 flex-wrap text-xs">
            <Link
              to="/dashboard/patient/history"
              className="px-3 py-1 rounded-full border text-slate-700"
            >
              View Scan History
            </Link>
            <Link
              to="/dashboard/patient/scans"
              className="px-3 py-1 rounded-full border text-slate-700"
            >
              My Scans
            </Link>
            <button
              onClick={exportPdf}
              className="px-3 py-1 rounded-full bg-slate-900 text-white"
            >
              Export PDF Report
            </button>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border p-4 space-y-4">
          <div className="flex flex-col lg:flex-row gap-6">
            <div className="flex-1 flex items-center justify-center">
              <img src={BrainHero} className="max-h-64 object-contain" />
            </div>

            <div className="w-full lg:w-60 space-y-3 text-xs">
              <div className="bg-slate-50 p-3 rounded-xl">
                <p className="font-semibold mb-1">Your Cognitive Stats</p>
                <div className="grid grid-cols-2 text-[11px] text-slate-700 gap-1">
                  <span>Oxygenation</span>
                  <span className="text-right">{data.oxygenation}%</span>
                  <span>Stress Level</span>
                  <span className="text-right">{data.stress}</span>
                  <span>Focus</span>
                  <span className="text-right">{data.focus}</span>
                </div>
              </div>

              <div className="bg-slate-50 p-3 rounded-xl">
                <p className="font-semibold mb-1">Cognitive Score</p>
                <p className="text-[11px]">{data.score} / 100</p>
              </div>
            </div>
          </div>

          <div className="flex gap-3 text-xs">
            <button className="px-4 py-1.5 rounded-full bg-sky-700 text-white font-medium">
              3D
            </button>
            <button className="px-4 py-1.5 rounded-full bg-slate-100 text-slate-700">
              Heat map
            </button>
            <button className="px-4 py-1.5 rounded-full bg-slate-100 text-slate-700">
              Raw
            </button>
          </div>
        </div>

        <div className="bg-white rounded-2xl shadow-sm border p-4">
          <h2 className="text-sm font-semibold">Doctor's Summary</h2>
          <p className="mt-1 text-[11px] text-slate-700">{data.doctorSummary}</p>

          <h3 className="mt-3 text-xs font-semibold">Detailed Notes</h3>
          <ul className="list-disc list-inside mt-1 text-[11px] text-slate-700 space-y-1">
            {data.doctorNotes.map((note) => (
              <li key={note}>{note}</li>
            ))}
          </ul>
        </div>
      </div>
    </DashboardLayout>
  );
};

export default PatientBrainDashboard;
